### PR TITLE
feat: support `NO_COLOR` and `FORCE_COLOR`, remove progress bar

### PR DESCRIPTION
**Pull request by uncenter**
Currently a draft as I have yet to reimplement the progress bar (personally I don't think the bar is necessary, but I'll try to add it - possibly using https://docs.rs/indicatif/0.17.8/indicatif/ this time). Switches to using https://docs.rs/yansi/latest/yansi/index.html for terminal coloring, which is configured to disable color with https://no-color.org/ or enable it with https://force-color.org/.

Related to a comment in #8.

### CODE REVIEW

**Comment by uncenter** [comment]
As mentioned in #8 by you:

> Hmm true progress bar is kinda useless I just added it for fun but it's good to have some sort of progress indicator. 🤔

I don't think a progress bar showing the downloading progress of each file makes sense, but maybe we can get a list of all files first and use that as the total to count up towards? Then again that seems architecturally difficult to do and doesn't maybe give enough value.

**Comment by alok8bb** [comment]
Uh yea, it's not really useful. And getting list of files and showing progress based on total count seems too much. But removing the progress bar will be weird, we'll have no progress being displayed.

**Comment by uncenter** [comment]
We can just print each of the filenames being downloaded? That's a pretty good indication of progress!

**Comment by alok8bb** [comment]
Yeah, that works! 😃

**Comment by alok8bb** [comment]
Thanks for adding `NO_COLOR` support! Great contribution, much appreciated.

**Pull request merged**
