### PR TITLE
Added `zip` feature and more code refactoring

### PR DESCRIPTION
**Pull request by winterrdog**
Hey @alok8bb ,

As I'd promised earlier, this is my first iteration on creating the `zip` feature. You can try to test it and lemme know if nothing's broken. Added some more features like allowing the user to download multiple URLs. You can look at the commits if you want more details on that

### CODE REVIEW

**Comment by alok8bb** [comment]
Hello @winterrdog, Sorry for the delay. I tested the build and the multiple URLs feature works perfectly. The zip feature didn't work for me, there was `missing field `name` at line 1 column 279` error while downloading the directories. I think that is a bug because now I'm getting the same error while cloning any directory as well, and If I remember correctly, I've encountered this error before too. I got this error after successfully cloning some directories, I used the same URL to clone and it worked perfectly right after compiling but after some time I started getting the same error for every single URL. 

`~/Temp
 cloneit https://github.com/alok8bb/BMI-Calculator-Android

            Getting: "https://github.com/alok8bb/BMI-Calculator-Android"
[1/3] 🔍  Validating url...
[2/3] 🚚  Downloading...
missing field `name` at line 1 column 279

        [+] Downloaded 1 file(s).`

**Comment by winterrdog** [comment]
Hey @alok8bb , I'll definitely check that out. Thanks for the response and effort to try out the PR . I'll be updating you soon

**Comment by winterrdog** [comment]
>  I used the same URL to clone and it worked perfectly right after compiling but after some time I started getting the same error for every single URL.

Maybe it's the github.com API frustrating our efforts🤔. Lemme carry out some more research

**Comment by winterrdog** [comment]
>  cloneit https://github.com/alok8bb/BMI-Calculator-Android
> 
>             Getting: "https://github.com/alok8bb/BMI-Calculator-Android"
> [1/3] 🔍  Validating url...
> [2/3] 🚚  Downloading...
> missing field `name` at line 1 column 279
> 
>         [+] Downloaded 1 file(s).

Woo! You do Java!?  😬 😬
 😅😅🙌. 

Anyways... after sometime that URL worked and got some Java that i quickly evaded!😅

**Comment by winterrdog** [comment]
> there was missing field name at line 1 column 279 error while downloading the directories. I think that is a bug because now I'm getting the same error while cloning any directory as well, and If I remember correctly, I've encountered this error before too.

It's caused by `serde_json`'s failure to correctly parse the `json` sent by the github.com api

**Pull request merged**
